[package]
name = "forezy_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = "0.42.0"
assert_macros = "2.9.2"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]